
export const PROJECT_UPLOAD_REQUEST = "PROJECT_UPLOAD_REQUEST";
export const PROJECT_UPLOAD_FAILURE = "PROJECT_UPLOAD_FAILURE";
export const GET_PROJECT_UPLOADS    = "GET_PROJECT_UPLOADS";
export const CREATE_PROJECT_UPLOADS = "CREATE_PROJECT_UPLOADS";